### ISSUE TITLE
Are the intensities of the pre-generated files already inverted to reflect cellular density?

### ISSUE THREAD

**Issue by gabocas** [caseypaquola/BigBrainWarp#7]
Dear Casey,
in your PLOSbiology paper from 2019, you mentioned that  "Computations were performed on inverted images, on which staining intensity reflects cellular density and soma size". Is the pre-generated standard set of staining intensity profiles for BigBrainWarp already inverted or shall I do that? (e.g. the file tpl-fs_LR_den-32k_desc-profiles.txt)

Thanks for your help.

Best,

Gabriel

**Comment by caseypaquola** [comment]
Hi Gabriel,

The intensities have not been inverted for the BigBrainWarp release. I recommend doing so at the start of your analysis pipeline.

For example (in matlab),
bbwDir='/path/to/BigBrainWarp/'
MP = reshape(dlmread([bbwDir '/spaces/tpl-fs_LR/tpl-fs_LR_den-32k_desc-profiles.txt']), 50, []);
MP = MP * -1;
plot(MP(:,100), fliplr(1:50))

If all goes correctly, then this will display a profile similar to Figure 1C, whereby higher "staining intensity" (x-axis) represents higher cellular density.

Hope that makes sense!

Best,
Casey

**Comment by gabocas** [comment]
Hi Casey, 
thanks for your help, it does make sense :)

All went correctly and I was able to reproduce your figure.

Best,

Gabriel
