### ISSUE TITLE
Is staining intensity an indicator of the soma volume ratio?

### ISSUE THREAD

**Issue by fachra** [caseypaquola/BigBrainWarp#8]
Dear Casey,

I am a PhD student studying diffusion MRI and I have a question about the interpretation of the staining intensity. I really hope you could help me with this question.

My project aims at estimating the soma volume ratio distribution of the human brain, especially in the cortex, using diffusion MRI. The soma volume ratio is defined as the ratio between the volume of somas and the volume of a brain voxel. In diffusion MRI, the voxel size is around 1mm^3. I developed a method that can estimate the soma volume ratio using diffusion MRI signals, and I want to use the BigBrain volume data as a reference to validate my model.

I download the volume data at 400um resolution from [LORIS](https://bigbrain.loris.ca/). The images are inverted so that high staining density corresponds to high cellular density or larger cell bodies. Can I further interpret the staining intensity as a qualitative indicator of the soma volume fraction? Does high staining intensity mean that somas occupy a large portion of the volume in that 400um voxel?

Thank you very much!

Best regards,
Chengran Fang

**Comment by caseypaquola** [comment]
Hi Chengran,

Yes, staining intensity in BigBrain proxies soma volume per voxel, in such a way that they should be positively correlated. It is important to note, however, that there can be other confounding factors that contribute to staining intensity in BigBrain, such as the overall staining of a section (some coronal sections of BigBrain are darker than others), as well as the presence of blood vessels and artifacts.

I hope that helps!

Best,
Casey

**Comment by fachra** [comment]
Thanks a lot! That is super helpful!
